CLJS-1031: Get Closure Compiler over https in the bootstrap script

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -66,7 +66,7 @@ cd ..
 echo "Fetching Google Closure compiler..."
 mkdir -p compiler
 cd compiler
-curl --retry 3 -O -s http://dl.google.com/closure-compiler/compiler-$CLOSURE_RELEASE.zip || { echo "Download failed."; exit 1; }
+curl --retry 3 -O -s https://dl.google.com/closure-compiler/compiler-$CLOSURE_RELEASE.zip || { echo "Download failed."; exit 1; }
 unzip -qu compiler-$CLOSURE_RELEASE.zip
 echo "Cleaning up Google Closure compiler archive..."
 rm compiler-$CLOSURE_RELEASE.zip
