CLJS-35: Google Closure Library HEAD
Allow bootstrap against HEAD of Google Closure library.
If script/bootstrap is called with --closure-library-head HEAD will be
used instead of most recently released version.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -14,13 +14,33 @@ rm -rf clojure-1.3.0/
 echo "Cleaning up Clojure archive..."
 rm clojure-1.3.0.zip
 
-echo "Fetching Google Closure library..."
 mkdir -p closure/library
 cd closure/library
-curl -O -s http://closure-library.googlecode.com/files/closure-library-20110323-r790.zip
-unzip -qu closure-library-20110323-r790.zip
-echo "Cleaning up Google Closure library archive..."
-rm closure-library-20110323-r790.zip
+if [ "x$1" = "x--closure-library-head" ] ; then
+    echo "Building against HEAD of Google Closure library..."
+
+    # Check if svn present
+    type svn >/dev/null 2>&1 || { echo >&2 "Need svn command to checkout HEAD of Google Closure library. Aborting."; exit 1; }
+
+    # Existing checkout?
+    set +e
+    svn info --non-interactive >/dev/null 2>&1
+    declare -i r=$?
+    set -e
+    if [ 0 -eq $r ] ; then
+        echo "Updating Google Closure library from HEAD..."
+        svn update -q --non-interactive
+    else
+        echo "Checking out HEAD of Google Closure library..."
+        svn checkout -q --non-interactive http://closure-library.googlecode.com/svn/trunk/ ./
+    fi
+else
+    echo "Fetching Google Closure library..."
+    curl -O -s http://closure-library.googlecode.com/files/closure-library-20110323-r790.zip
+    unzip -qu closure-library-20110323-r790.zip
+    echo "Cleaning up Google Closure library archive..."
+    rm closure-library-20110323-r790.zip
+fi
 cd ..
 
 echo "Fetching Google Closure compiler..."
