change bootstrap script so we get the same version of the Closure Compiler declared in the POM

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -3,6 +3,7 @@
 set -e
 
 CLOJURE_RELEASE="1.6.0"
+CLOSURE_RELEASE="v20140625"
 DJSON_RELEASE="0.2.3"
 GCLOSURE_LIB_RELEASE="0.0-20140718-946a7d39"
 RHINO_RELEASE="1_7R3"
@@ -65,10 +66,7 @@ cd ..
 echo "Fetching Google Closure compiler..."
 mkdir -p compiler
 cd compiler
-curl --retry 3 -O -s https://dl.google.com/closure-compiler/compiler-latest.zip || { echo "Download failed."; exit 1; }
-unzip -qu compiler-latest.zip
-echo "Cleaning up Google Closure compiler archive..."
-rm compiler-latest.zip
+curl --retry 3 -O -s https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/$CLOSURE_RELEASE/closure-compiler-$CLOSURE_RELEASE.jar || { echo "Download failed."; exit 1; }
 cd ../..
 
 if [ "$1" = "--closure-library-head" ] ; then
@@ -88,7 +86,7 @@ echo "Cleaning up Rhino archive..."
 rm rhino$RHINO_RELEASE.zip
 
 echo "Copying closure/compiler/compiler.jar to lib/compiler.jar"
-cp closure/compiler/compiler.jar lib
+cp closure/compiler/closure-compiler-$CLOSURE_RELEASE.jar lib
 
 echo "Fetching tools.reader $TREADER_RELEASE ..."
 curl --retry 3 -O -s https://repo1.maven.org/maven2/org/clojure/tools.reader/$TREADER_RELEASE/tools.reader-$TREADER_RELEASE.jar || { echo "Download failed."; exit 1; }
