add transit-clj as a provided dep

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -5,6 +5,7 @@ set -e
 CLOJURE_RELEASE="1.8.0"
 CLOSURE_RELEASE="20160315"
 DJSON_RELEASE="0.2.6"
+TRANSIT_RELEASE="0.8.285"
 GCLOSURE_LIB_RELEASE="0.0-20151016-61277aea"
 RHINO_RELEASE="1_7R5"
 TREADER_RELEASE="1.0.0-beta1"
@@ -32,6 +33,13 @@ echo "Copying data.json-$DJSON_RELEASE.jar to lib/data.json-$DJSON_RELEASE.jar..
 cp data.json-$DJSON_RELEASE.jar lib/data.json-$DJSON_RELEASE.jar
 echo "Cleaning up data.json..."
 rm data.json-$DJSON_RELEASE.jar
+
+echo "Fetching transit-clj..."
+curl --retry 3 -O -s https://repo1.maven.org/maven2/com/cognitect/transit-clj/$TRANSIT_RELEASE/transit-clj-$TRANSIT_RELEASE.jar || { echo "Download failed."; exit 1; }
+echo "Copying transit-cjl-$TRANSIT_RELEASE.jar to lib/transit-clj-$TRANSIT_RELEASE.jar..."
+cp transit-clj-$TRANSIT_RELEASE.jar lib/transit-clj-$TRANSIT_RELEASE.jar
+echo "Cleaning up data.json..."
+rm transit-clj-$TRANSIT_RELEASE.jar
 
 echo "Fetching Google Closure library..."
 mkdir -p closure/library
